Repository origo-map/origo, pull requests merged in 2020-12, with the labels that each got.

#1045 adds jsconfig
  jsconfig.json
Labels: bug

#1048 Add source-map loader
  package-lock.json
  package.json
  tasks/webpack.common.js
Labels: bug, enhancement

#1052 Method that takes a GeoJSON and returns a WKT string
  src/maputils.js
Labels: enhancement, in progress

#1053 Print settings have separate collapse container class
  scss/ui/_collapse.scss
  src/controls/print/print-settings.js
  src/ui/collapse.js
Labels: bug, in progress

#1055 Package updates
  package-lock.json
  package.json
  tasks/webpack.prod.js
Labels: enhancement, in progress

#1062 Jq replace
  origo.js
  package-lock.json
  package.json
  src/controls/editor/addons/searchList/searchList.js
  src/controls/editor/addons/searchList/utils/attachBtnEvent.js
  src/controls/editor/addons/searchList/utils/awesomeImage.js
  src/controls/editor/addons/searchList/utils/fetchImg.js
  src/controls/editor/addons/searchList/utils/moveBtn.js
  src/controls/editor/agstransaction.js
  src/controls/editor/drawtools.js
  src/controls/editor/editdispatcher.js
  src/controls/editor/edithandler.js
  src/controls/editor/editorlayers.js
  src/controls/editor/editortoolbar.js
  src/controls/editor/editsstore.js
  src/controls/editor/transactionhandler.js
  src/controls/editor/wfstransaction.js
  src/controls/legend/overlays.js
  src/controls/offline/downloadhandler.js
  src/controls/offline/geojson.js
  src/controls/offline/offlinestore.js
  src/controls/offline/topojson.js
  src/controls/offline/wfs.js
  src/controls/search.js
  src/controls/zoom.js
  src/featureinfo.js
  src/featurelayer.js
  src/getfeature.js
  src/getfeatureinfo.js
  src/infowindow.js
  src/layer/group.js
  src/layer/wms.js
  src/loadresources.js
  src/popup.js
  src/style/styletypes.js
  src/ui/modal.js
  src/utils/legendrender.js
  src/utils/mapsize.js
  src/utils/rendererror.js
  src/utils/validate.js
  tasks/webpack.common.js
Labels: bug, critical, enhancement, in progress

#1070 adds debugger config
  .vscode/launch.json
  tasks/webpack.lint.dev.js
Labels: enhancement, in progress
